import os
import google.generativeai as genai

from ...domain import BaseChat

class Gemini(BaseChat):
    """
    Gemini is a class that represents a chatbot using the Google Generative AI.
    It inherits from the BaseChat class.
    """

    def __init__(self):
        """
        Initializes the Gemini chatbot.
        It sets up the Google Generative AI by configuring the API key.
        """
        genai.configure(api_key=os.getenv("GOOGLE_API_KEY"))

    def chat(self, prompt: str) -> str:
        """
        Sends a chat prompt to the Google Generative AI model and returns the response.

        Parameters:
        prompt (str): The chat prompt to be sent to the model.

        Returns:
        str: The response generated by the model.
        """
        model = genai.GenerativeModel(model_name=os.getenv("MODEL_NAME"))
        chat_response = model.generate_content(f"""\n{prompt} \n""")
        return chat_response.text